openapi: 3.0.3
info:
  title: RESTful API for Grocery Store
  description: API for managing users, categories, and products in a grocery store web application
  
  version: 1.0.0
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /login:
    post:
      summary: Authenticate user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: User authenticated successfully
        '401':
          description: Invalid credentials
  /users:
    post:
      summary: Create a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: User added successfully
        '400':
          description: Required fields are missing
        '409':
          description: User with this email already exists
        '500':
          description: Failed to add user
  /users/{user_id}:
    put:
      summary: Update user information
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
      responses:
        '200':
          description: User updated successfully
        '400':
          description: Invalid email or missing email
        '404':
          description: User not found
        '500':
          description: Failed to update user
    delete:
      summary: Delete user
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: User deleted successfully
        '404':
          description: User not found
        '500':
          description: Failed to delete user
  /categories:
    get:
      summary: Get all categories
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
    post:
      summary: Create a new category (only for managers)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                cat_image:
                  type: string
      responses:
        '201':
          description: Category added successfully
        '400':
          description: Required fields are missing
        '403':
          description: Only managers are allowed to add categories
        '409':
          description: Category already exists
        '500':
          description: Failed to add category
    put:
      summary: Update category (only for managers)
      security:
        - bearerAuth: []
      parameters:
        - name: section_id
          in: query
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                cat_image:
                  type: string
      responses:
        '200':
          description: Category updated successfully
        '400':
          description: Required fields are missing
        '403':
          description: Only managers are allowed to update categories
        '404':
          description: Category not found
        '500':
          description: Failed to update category
    delete:
      summary: Delete category (only for managers)
      security:
        - bearerAuth: []
      parameters:
        - name: section_id
          in: query
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Category deleted successfully
        '403':
          description: Only managers are allowed to delete categories
        '404':
          description: Category not found
        '500':
          description: Failed to delete category
  /categories/{section_id}:
    get:
      summary: Get category by section_id
      parameters:
        - name: section_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '404':
          description: Category not found
  /products:
    get:
      summary: Get all products
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
    post:
      summary: Create a new product (only for managers)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                manufacture_date:
                  type: string
                rate_per_unit:
                  type: number
                unit:
                  type: string
                stock:
                  type: number
                image:
                  type: string
                section_id:
                  type: integer
      responses:
        '201':
          description: Product added successfully
        '400':
          description: Missing required fields
        '403':
          description: Only managers are allowed to add products
        '500':
          description: Failed to add product
    put:
      summary: Update product (only for managers)
      security:
        - bearerAuth: []
      parameters:
        - name: product_id
          in: query
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                manufacture_date:
                  type: string
                rate_per_unit:
                  type: number
                unit:
                  type: string
                stock:
                  type: number
                image:
                  type: string
                section_id:
                  type: integer
      responses:
        '200':
          description: Product updated successfully
        '400':
          description: Invalid or missing fields
        '403':
          description: Only managers are allowed to update products
        '404':
          description: Product not found
        '500':
          description: Failed to update product
    delete:
      summary: Delete product (only for managers)
      security:
        - bearerAuth: []
      parameters:
        - name: product_id
          in: query
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Product deleted successfully
        '403':
          description: Only managers are allowed to delete products
        '404':
          description: Product not found
        '500':
          description: Failed to delete product
  /products/{product_id}:
    get:
      summary: Get product by product_id
      parameters:
        - name: product_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '404':
          description: Product not found
